### PR TITLE
Fix mojank in EffectInstance

### PR DESCRIPTION
**Pull request by MaxNeedsSnacks**
This is another one of those mojank patches by forge I discovered while porting KubeJS-UI

Might be useful to have in architectury to get rid of some vanilla bugs devs moving from exclusively Forge-based setups may encounter

### CODE REVIEW

**Comment by shedaniel** [comment]
This is going to break some fabric mods depending on this broken behaviour, i.e. the armour texture is limited to the minecraft namespace, and you know what people did? They just add their texture to the minecraft namespace to circumvent the issue.

**Comment by MaxNeedsSnacks** [comment]
How would you say we should circumvent that? Obviously this isn't intentional on Mojang's end and the original format is still supported, i.e. mods adding things to the mc namespace SPECIFICALLY won't break with this, but this (and similar issues like it) will probably be a problem a fair few modders migrating from Forge will encounter on their way.

**Comment by shedaniel** [comment]
It is _possible_ to do both formats (by detecting via the ResourceManager), but it is annoying.

**Comment by MaxNeedsSnacks** [comment]
The thing I'm wondering is: Would this actually break with anything?
The original code throws a ResourceLocationException when given something like `fabricmod:mymodel`, so no mod should be using that in production either (and as you said, they don't and instead would instead just use a string id like `mymodel`, which under this new impl would still be put under the `minecraft` namespace).

**Comment by shedaniel** [comment]
Right indeed, this should be fine then, we can probably merge this now.

**Pull request merged**
