### PR TITLE
Possible fixes for BE syncing on Forge

### PR DESCRIPTION
**Pull request by MaxNeedsSnacks**
Experimenting around with different ways to fix BE syncing issues on Forge
(originally discovered in FTB Quests that BEs don't seem to properly sync their data by default)

### CODE REVIEW

**Comment by LatvianModder** [comment]
nice

**Comment by MaxNeedsSnacks** [comment]
also... nice

**Comment by MaxNeedsSnacks** [comment]
nice

**Comment by shedaniel** [comment]
is this intended? you are supposed to call that super saveMetadata method in your own saveClientData method

**Comment by MaxNeedsSnacks** [comment]
Since saveMetadata is a private method that's only used in base BlockEntity, I'm guessing that would be getUpdateTag, however if that's the case I don't 100% get what to do with the input tag parameter in saveClientData on Forge as modders would obviously want to use the result of `super.getUpdateTag()` instead to preserve their superclass's data as well.

Also is there any case where a BE would **not** want its super's metdata added on top, out of curiosity?

**Comment by shedaniel** [comment]
Actually, not `saveMetadata`, I meant the normal `save`.

**Pull request closed without merging**
