### PR TITLE
Fix Support for 41.0.64

### PR DESCRIPTION
**Pull request by shedaniel**
Untested yet! Please test the attached file! (Unzip it, there is a jar inside)  
[architectury-5.7.9999-forge.zip](https://github.com/architectury/architectury-api/files/9071962/architectury-5.7.9999-forge.zip)

We might want to bump a minor on this due to how big this change is.

### CODE REVIEW

**Review by MaxNeedsSnacks — APPROVED** [review]
The ParticleProviderRegistry one seems a little messy, but... should work out of the box. Rest looks good to me too!

**Comment by MaxNeedsSnacks** [comment]
Note: This still needs more active testing, I have only been able to review this on a surface-level because I am currently busy with other things, unfortunately

**Comment by gigabit101** [comment]
Tested with all of mine/CreeperHosts mods and everything seems to be working fine

**Comment by shedaniel** [comment]
> Tested with all of mine/CreeperHosts mods and everything seems to be working fine

@gigabit101 Thanks for testing it!

**Comment by gigabit101** [comment]
> > Tested with all of mine/CreeperHosts mods and everything seems to be working fine
> 
> @gigabit101 Thanks for testing it!

@shedaniel  Not a problem at all, I had already started doing the "port" for you before going to lunch so you managed to beat me lol

**Pull request merged**
