### PR TITLE
Registry Replacements (#430)

### PR DESCRIPTION
**Pull request by qyl27**
Replace vanilla items with register() on fabric.  
(Tested on my machine.)

### CODE REVIEW

**Comment by MaxNeedsSnacks** [comment]
Hmm, honestly I would prefer if registry replacement was **explicit** on both instead of implicit, so maybe we should instead consider making a registerOrOverride method?

**Comment by qyl27** [comment]
> Hmm, honestly I would prefer if registry replacement was **explicit** on both instead of implicit, so maybe we should instead consider making a registerOrOverride method?

Well, maybe that's right.  
I will change it to a explicit method named `registerOrOverride`.

**Comment by shedaniel** [comment]
After some discussion on Discord, I believe we don't want to support registry replacements seeing how NeoForge no longer supports it after the Registry Rework and fabric never encouraged it. Alternative solutions should be used instead, albeit mixins or etc.

Some checks can be added to the forge register() method to warn potential registry replacements instead.

**Comment by qyl27** [comment]
> After some discussion on Discord, I believe we don't want to support registry replacements seeing how NeoForge no longer supports it after the Registry Rework and fabric never encouraged it. Alternative solutions should be used instead, albeit mixins or etc.
> 
> Some checks can be added to the forge register() method to warn potential registry replacements instead.

Ah, okay.

**Comment by Jab125** [comment]
> After some discussion on Discord, I believe we don't want to support registry replacements seeing how NeoForge no longer supports it after the Registry Rework and fabric never encouraged it. Alternative solutions should be used instead, albeit mixins or etc.
> 
> Some checks can be added to the forge register() method to warn potential registry replacements instead.

**Pull request closed without merging**
